# Generated by Django 4.2.4 on 2023-10-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_following'),
        ('images', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
